# Generated by Django 4.0.2 on 2022-06-23 22:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlteiaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_code', models.CharField(max_length=200, unique=True)),
                ('cashew_tree_cover', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommuneSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200, unique=True)),
                ('cashew_tree_cover', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200, unique=True)),
                ('cashew_tree_cover', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_tree_name', models.CharField(max_length=200, unique=True)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('owner_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('female', 'Others')], default='others', max_length=6)),
                ('owner_date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mother_tree_address', models.CharField(max_length=200)),
                ('owner_address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('plantation_id', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('certified', models.BooleanField(default=False)),
                ('certified_by', models.BigIntegerField(blank=True)),
                ('certified_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursery_name', models.CharField(max_length=200, unique=True)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('nursery_address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('current_area', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('partner', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('number_of_plants', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_name', models.CharField(max_length=200, unique=True)),
                ('plantation_code', models.CharField(max_length=200, unique=True)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('owner_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('female', 'Others')], default='others', max_length=6)),
                ('total_trees', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('current_area', models.FloatField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_id', models.CharField(max_length=200, unique=True)),
                ('alteia_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('institution', models.CharField(choices=[('atda4', 'ATDA4'), ('benincàju', 'BENINCÀJU'), ('other', 'OTHER')], default='other', max_length=9)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('number_of_participant', models.IntegerField()),
                ('department', models.CharField(default='', max_length=200, null=True)),
                ('commune', models.CharField(default='', max_length=200, null=True)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trainingmodule')),
                ('trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='NurseryPlantsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField()),
                ('total_plants', models.BigIntegerField()),
                ('total_grafted', models.BigIntegerField()),
                ('total_graft_holders', models.BigIntegerField()),
                ('polyclonal', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
                ('nursery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='BeninYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('plantation_code', models.CharField(max_length=200)),
                ('surface_area', models.FloatField(null=True)),
                ('total_yield_kg', models.FloatField()),
                ('total_yield_per_ha_kg', models.FloatField()),
                ('total_yield_per_tree_kg', models.FloatField()),
                ('sex', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=60)),
                ('total_number_trees', models.FloatField()),
                ('total_sick_trees', models.FloatField()),
                ('total_dead_trees', models.FloatField()),
                ('total_trees_out_of_prod', models.FloatField()),
                ('plantation_age', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('year', models.IntegerField()),
                ('plantation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plantation')),
            ],
        ),
    ]
