# Generated by Django 4.0.2 on 2022-02-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alteiadata_beninyield_communesatellite_deptsatellite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qar',
        ),
    ]
