# Generated by Django 4.0.2 on 2022-05-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_trainer_trainingmodule_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='commune',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
    ]
