# Generated by Django 4.0.2 on 2022-06-08 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('authentication', '0001_initial'), ('authentication', '0002_remove_remuser_email_remove_remuser_first_name_and_more'), ('authentication', '0003_remuser_email_remuser_first_name_remuser_last_name_and_more'), ('authentication', '0004_alter_remuser_email'), ('authentication', '0005_remove_remuser_created_by_and_more'), ('authentication', '0006_alter_remuser_organization'), ('authentication', '0007_remuser_email'), ('authentication', '0008_delete_alteiadata_remove_beninyield_plantation_id_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('e_mail', models.EmailField(max_length=254)),
                ('website', models.URLField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.remorganization')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.remrole')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
