# Generated by Django 4.0.1 on 2022-01-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='username',
        ),
        migrations.AddField(
            model_name='remuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
