# Generated by Django 4.0.1 on 2022-01-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_remuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='username',
        ),
    ]
