# Generated by Django 4.0.1 on 2022-01-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_remuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.remorganization'),
        ),
    ]
