# Generated by Django 4.0.1 on 2022-01-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlteiaData',
        ),
        migrations.RemoveField(
            model_name='beninyield',
            name='plantation_id',
        ),
        migrations.DeleteModel(
            name='CommuneSatellite',
        ),
        migrations.DeleteModel(
            name='DeptSatellite',
        ),
        migrations.DeleteModel(
            name='MotherTree',
        ),
        migrations.RemoveField(
            model_name='nurseryplantshistory',
            name='nursery_id',
        ),
        migrations.DeleteModel(
            name='SpecialTuple',
        ),
        migrations.DeleteModel(
            name='BeninYield',
        ),
        migrations.DeleteModel(
            name='Nursery',
        ),
        migrations.DeleteModel(
            name='NurseryPlantsHistory',
        ),
        migrations.DeleteModel(
            name='Plantation',
        ),
    ]
